name: Update market.json

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
  push:
    paths:
      - '.github/**'  # Trigger when updates are made to the .github folder
      - 'scripts/**'
      - 'skeleton.json'

jobs:
  update-market:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          cd scripts
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run the Python script
      - name: Run Python script
        run: |
          cd scripts
          python3 filler.py

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated market.json" || echo "ignore commit failure, proceed"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
